### ISSUE TITLE
Query/Retrieve using the adapter

### ISSUE THREAD

**Issue by cdoshi** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#46]
Is it possible to query/retrieve my local PACS using the healthcare-dicom-dicomweb-adapter? If so, how do you do it? I was able to query/retrieve data from the data stores using PACS. I need the other way around.

**Comment by pavertomato** [comment]
> Is it possible to query/retrieve my local PACS using the healthcare-dicom-dicomweb-adapter? If so, how do you do it? I was able to query/retrieve data from the data stores using PACS. I need the other way around.

Hi @cdoshi, could you please provide more information about your setup? short answer is - yes, it's possible to run adapters locally for your DIMSE instances https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/wiki/Running-Docker-image-locally

**Comment by cdoshi** [comment]
@pavertomato So the setup is that the I am running the dicom adapter locally on my machine and I have the PACS setup on my local machine as well. I can trigger query/retrieve from PACS to upload image to cloud via the adapter. What I really want to do is trigger a query/retrieve from adapter to PACS via a command or some other way. I am able to find the documentation for the same.

**Comment by red1408** [comment]
@cdoshi , do you mean to use local PACS instead of cloud healthcare api as the underlying service? In general, this should work as long as said PACS supports QIDO-RS and WADO-RS. You just need to set --dicomweb_address parameter to it's endpoint. 

I used https://github.com/dcm4che/dcm4chee-arc-light with adapter during development and didn't run into any problems. Though on deeper inspection some implementation details of adapter may be specific to healthcare api.

**Comment by cdoshi** [comment]
Thanks @red1408 for the clarification!
